relevant_tags_home = ['name', 'severity', 'message']

relevant_tags_prom = ['name', 'env', 'region', 'severity',
                      'instance',  'startsAt',   'endsAt', 'description', 'fingerprint']

relations = [('name', 'name'), ('message', 'description'), ('severity', 'severity')]


# Alert tags dataset

regions = [
    "us-central1",
    "us-east1",
    "us-east4",
    "us-west1",
    "us-west2",
    "us-west3",
    "us-west4",
    "northamerica-northeast1",
    "southamerica-east1",
    "southamerica-west1",
    "europe-north1",
    "europe-west1",
    "europe-west2",
    "europe-west3",
    "europe-west4",
    "europe-west6",
    "europe-central2",
    "asia-east1",
    "asia-east2",
    "asia-northeast1",
    "asia-northeast2",
    "asia-northeast3",
    "asia-south1",
    "asia-south2",
    "asia-southeast1",
    "asia-southeast2",
    "australia-southeast1",
    "australia-southeast2",
    "africa-south1"
]

severity_levels = [
    "critical",
    "high",
    "medium",
    "low",
    "warning",
    "info",
    "debug"
]

environments = [
    "production",
    "staging",
    "development",
    "testing",
    "qa",          # Quality Assurance
    "sandbox",
    "integration",
    "pre-production",
    "demo",
    "backup"
]

alerts = {
    "CPUUsageHigh": "The CPU usage has exceeded a defined threshold.",
    "MemoryUsageHigh": "The memory usage has exceeded a defined threshold.",
    "DiskSpaceLow": "The available disk space is below a defined threshold.",
    "NetworkLatencyHigh": "Network latency has exceeded acceptable limits.",
    "ServiceDown": "A critical service is down or not responding.",
    "DatabaseConnectionError": "Unable to connect to the database.",
    "ApplicationError": "An application error has occurred.",
    "SecurityBreach": "A potential security breach has been detected.",
    "UnauthorizedAccess": "Unauthorized access attempt detected.",
    "BackupFailed": "Scheduled backup has failed.",
    "HardwareFailure": "A hardware component has failed.",
    "TemperatureHigh": "The temperature of a component or system is too high.",
    "PowerFailure": "A power failure or outage has occurred.",
    "ConfigurationChange": "A critical configuration has been changed.",
    "ServiceDegraded": "A service is running but its performance is degraded.",
    "ResourceExhaustion": "A system resource is nearly exhausted.",
    "ProcessCrash": "A critical process has crashed.",
    "DependencyFailure": "A failure in a dependent system or service.",
    "AuthenticationFailure": "Authentication process has failed.",
    "TimeoutError": "A request or process has timed out.",
    "HighErrorRate": "High error rate detected in application logs.",
    "UpdateFailed": "System or application update has failed.",
    "SlowQuery": "A database query is taking too long to execute.",
    "QueueDepthHigh": "The depth of a queue has exceeded a threshold.",
    "ServiceRestarted": "A service has been restarted unexpectedly.",
    "CertificateExpiry": "A security certificate is about to expire.",
    "FileSystemCorruption": "File system corruption detected.",
    "InsufficientPermissions": "A process or user lacks necessary permissions.",
    "ServiceDependencyDown": "A service dependency is down or unresponsive.",
    "ServiceMemoryLeak": "A service is experiencing a memory leak.",
    "NetworkCongestion": "Network is experiencing congestion.",
    "DNSResolutionFailed": "DNS resolution is failing.",
    "ServiceDeploymentFailed": "A service deployment has failed.",
    "StorageIOError": "I/O error on a storage device.",
    "HighLoadAverage": "System load average is high.",
    "HardwareOverheating": "Hardware component is overheating.",
    "DataIntegrityError": "Data integrity check failed.",
    "LicenseExpiry": "A software license is about to expire.",
    "ServiceRateLimitExceeded": "Rate limit for a service has been exceeded."
}


service_names = [
    "Kubernetes",
    "DockerSwarm",
    "ApacheMesos",
    "RedHatOpenShift",
    "HashiCorpNomad",
    "Rancher",
    "AmazonElasticKubernetesService",
    "GoogleKubernetesEngine",
    "AzureKubernetes Service",
    "TanzuKubernetesGrid",
    "Portainer",
    "AmazonS3",
    "GoogleCloudStorage",
    "MicrosoftAzureBlobStorage",
    "Dropbox",
    "Box",
    "AmazonRDS",
    "GoogleCloudSpanner",
    "MicrosoftAzureSQLDatabase",
    "MongoDBAtlas",
    "FirebaseRealtimeDatabase",
    "Datadog",
    "NewRelic",
    "Splunk",
    "Grafana",
    "Prometheus",
    "Jenkins",
    "CircleCI",
    "TravisCI",
    "GitLabCI",
    "Bamboo",
    "Okta",
    "Auth0",
    "PaloAltoNetworks",
    "CiscoSecure",
    "NortonSecurity",
    "Slack",
    "MicrosoftTeams",
    "Zoom",
    "GoogleMeet",
    "Trello",
    "VeeamBackup",
    "AcronisBackup",
    "Carbonite",
    "Backblaze",
    "Rubrik",
    "Cloudflare",
    "Akamai",
    "AmazonCloudFront",
    "GoogleCloudCDN",
    "Fastly",
    "GoogleBigQuery",
    "AmazonRedshift",
    "MicrosoftPowerBI",
    "Tableau",
    "Snowflake",
    "AWSIAM",
    "AzureActiveDirectory",
    "GoogleIdentityPlatform",
    "LastPass",
    "OneLogin"
]

